version: '3'
services:
  nginx: 
    image: nginx:latest
    volumes:
       - ./conf.d:/etc/nginx/conf.d
#      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    links:
      - "dashboards"
      - "billing"
    networks:
      - flaskapp

  dashboards:
    image: jcdemo/flaskapp
    volumes:
      - ./dashboards/src:/src
    ports:
      - 5000:5000
    networks:
      - flaskapp

  billing:
    image: jcdemo/flaskapp
    volumes:
      - ./billing/src:/src
    ports:
      - 5001:5000
    networks:
      - flaskapp
  
networks:
  flaskapp:
    driver: bridge
