version: '3'
services:
  nginx: 
    image: nginx:latest
    volumes:
       - ./conf.d:/etc/nginx/conf.d
#      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  dashboards:
    image: jcdemo/flaskapp
    volumes:
      - ./dashboards/src:/src
    expose:
      - "5000"

  billing:
    image: jcdemo/flaskapp
    volumes:
      - ./billing/src:/src
    expose:
      - "5000"
